before_script:
  - env | grep rvm
  - rvm use 2.4@phillumeny --create
  - ruby -v
  - which ruby
  - bundle update --jobs $(nproc)

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop -D
