AllCops:
  Exclude:
    - tmp/dummy/**/*

EmptyLinesAroundBlockBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

LineLength:
  Max: 125

WordArray:
  Enabled: false
