EmptyLinesAroundBlockBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

LineLength:
  Max: 125

PredicateName:
  Exclude:
    - lib/phillumeny/active_record.rb
